/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cx_project_zhihudaliy_c_API */

#ifndef _Included_com_cx_project_zhihudaliy_c_API
#define _Included_com_cx_project_zhihudaliy_c_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getThemesUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getThemesUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getStartImageUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getStartImageUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getLatestUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getLatestUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getBeforeUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getBeforeUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getTheme
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getTheme
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getNewsDetail
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getNewsDetail
  (JNIEnv *, jclass);

/*
 * Class:     com_cx_project_zhihudaliy_c_API
 * Method:    getNewsDetailExtra
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cx_project_zhihudaliy_c_API_getNewsDetailExtra
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
